-- Generated by scripts/convert-repop-info.py; do not edit by hand.
rod.repop_info = {
    ["A Moment in Nature"] = {
        timer_minutes = 8,
        messages = {
            "A murder of crows wings over the forest.",
        },
    },
    ["Abattoir Asylum"] = {
        timer_minutes = 14,
        messages = {
            "A symphony of madness arises from the depths of the Abattoir Asylum as dark powers renew maniacal life...",
        },
    },
    ["Abishai's Morgue"] = {
        timer_minutes = 25,
        messages = {
            "The grating cry of a raven is heard in the distance but fades away unanswered.",
        },
    },
    ["Along the Forest Path"] = {
        messages = {
            "With a slow creak, the trees move in the wind.",
        },
    },
    ["The Ancient City of Aurora"] = {
        timer_minutes = 14,
        messages = {
            "A soothing feeling surrounds Aurora as peace is restored.",
        },
    },
    ["Antall, the Lost Harbor"] = {
        timer_minutes = 9,
        messages = {
            "Dark waves shift slowly between past and present...",
        },
    },
    ["Asgard Nexus"] = {
        messages = {
            "The struggle for dominance continues...",
        },
    },
    ["Ashen Forest"] = {
        timer_minutes = 25,
        messages = {
            "A scream is heard from deep within the Ashen Forest.",
        },
    },
    ["Astral Plane"] = {
        messages = {
            "The astral field glitters with a thousand points of light for a moment...",
        },
    },
    ["Azure Sea"] = {
        messages = {
            "The endless eastern ocean draws your mind into a daze...",
        },
    },
    ["Barren Peaks of Tahjliera"] = {
        messages = {
            "An eerie howl echoes through the rocky peaks, sending shivers down your spine...",
        },
    },
    ["Barrik's Keep"] = {
        messages = {
            "You hear the scurry of feet behind you ... BIG feet!",
        },
    },
    ["Bartok Grove"] = {
        messages = {
            "Like a fine wine, things improve with age.",
        },
    },
    ["Blasted Lands"] = {
        timer_minutes = 24,
        messages = {
            "The ashy winds blow about you, leaving you covered in a film of dust and sand.",
        },
    },
    ["Blood Sea"] = {
        messages = {
            "The ocean bleeds new life...",
        },
    },
    ["Coral Depths"] = {
        timer_minutes = 15,
        messages = {
            "A blast from Triton's horn signifies the battle of good versus evil rages on.",
        },
    },
    ["Crystalmir Lake"] = {
        messages = {
            "The haunting voice drifts over the water in song.",
        },
    },
    ["Cursed Lands"] = {
        timer_minutes = 15,
        messages = {
            "The desecrated Clan Tree mourns for a more prosperous time.",
        },
    },
    ["D'Morian's Lands"] = {
        timer_minutes = 15,
        messages = {
            "A plaintive sob echoing across the lake is answered by a ghostly keening.",
        },
    },
    ["Darkhaven Art Gallery"] = {
        timer_minutes = 15,
        messages = {
            "A low murmur echoes through the Gallery as more critics enter the building.",
        },
    },
    ["Desert of Despair"] = {
        messages = {
            "Hot, arid winds roll off the sands of the great desert....",
        },
    },
    ["Dragon Cult"] = {
        timer_minutes = 13,
        messages = {
            "A hollow chant can be heard from somewhere far below...",
        },
    },
    ["Dragon Tower"] = {
        messages = {
            "The cries of sparring dragons echo eerily in the distance.",
        },
    },
    ["Dragon's Pass"] = {
        timer_minutes = 20,
        messages = {
            "The cry of a hungry dragon echoes throughout the pass as it takes flight.",
        },
    },
    ["Drow City"] = {
        messages = {
            "A solemn chant begins in the distance.",
        },
    },
    ["Dungeon"] = {
        timer_minutes = 15,
        messages = {
            "You hear the echo of a prisoner screaming.",
        },
    },
    ["Dunhill Demesnes"] = {
        timer_minutes = 20,
        messages = {
            "The wail of the Hunter's horn echoes across the forests...",
        },
    },
    ["Dwarven Catacombs"] = {
        messages = {
            "The sound of shuffling footsteps is audible behind you...",
        },
    },
    ["Dylan's Area"] = {
        messages = {
            "The winds of change swirl around you like a bad Van Gogh.",
        },
    },
    ["Eastern Trade Route"] = {
        timer_minutes = 16,
        messages = {
            "The sounds of a wagon clattering down the road can be heard in the distance.",
        },
    },
    ["Elemental Canyon"] = {
        timer_minutes = 16,
        messages = {
            "New elements arise to join the war against each other.",
        },
    },
    ["Emerald Hills"] = {
        timer_minutes = 11,
        messages = {
            "A cool breeze blows in from the Emerald Hills...",
        },
    },
    ["Forest of Tears"] = {
        timer_minutes = 15,
        messages = {
            "The forest begins to swell in the heat, enveloping its occupants.",
        },
    },
    ["Forgotten Woods"] = {
        timer_minutes = 33,
        messages = {
            "The howl of a wolf echoes in the distance...",
        },
    },
    ["Galaxy"] = {
        messages = {
            "With a big bang, the Galaxy begins anew...",
        },
    },
    ["Gauntlet"] = {
        messages = {
            "A hoarse battlecry echoes over the hills.",
        },
    },
    ["Graveyard"] = {
        messages = {
            "A howl echoes mournfully from the nearby forest...",
        },
    },
    ["Great Eastern Desert"] = {
        messages = {
            "The desert sands whip madly about you...",
        },
    },
    ["Green Forest"] = {
        messages = {
            "The ancient trees almost seem to grow a little as they continue to age.",
        },
    },
    ["Halls of Knowledge"] = {
        silent = true,
        messages = {
            "The spirit guides roam the halls, in search of new students.",
        },
    },
    ["Haven of Everlasting Light"] = {
        messages = {
            "The Cathedral bell echoes throughout the land, as a solemn epitaph to the dead.",
        },
    },
    ["High Tower of Sorcery"] = {
        timer_minutes = 15,
        messages = {
            "A mass of tingling magic envelops you...",
        },
    },
    ["Keep of Mahn-tor"] = {
        messages = {
            "The disgusting cry of a large beast rings through the air, followed by the sounds of battle.",
        },
    },
    ["The King's Castle"] = {
        timer_minutes = 18,
        messages = {
            "Strains of soft music echo throughout the ancient halls.",
        },
    },
    ["Kingdom of Juargan"] = {
        messages = {
            "A loud cheer erupts as another group of dwarves strikes a vein of precious ore.",
        },
    },
    ["Knights of the Round"] = {
        timer_minutes = 35,
        messages = {
            "A Knight cries out, \"A King without a sword... a land without a King!\"",
        },
    },
    ["Kontaur"] = {
        messages = {
            "Another scream is heard as balrog and elf wage battle.",
        },
    },
    ["La Chute D'eau De L'ancients"] = {
        timer_minutes = 27,
        messages = {
            "A fine mist fills the air as the forces of the warring magie clash in an eternal battle...",
        },
    },
    ["Lake of Tich'Pyga"] = {
        timer_minutes = 14,
        messages = {
            "The cry of a loon echoes across the rippling surface of the loch.",
        },
    },
    ["Land of the Fire Newts"] = {
        messages = {
            "From the bowels of this blackened mountain, a sharp cracking can be heard...",
        },
    },
    ["Machine Dreams"] = {
        timer_minutes = 17.5,
        messages = {
            "A violet, mechanical sound rises from below and dissipates like mist.",
        },
    },
    ["Miden'nir"] = {
        messages = {
            "Black clouds obscure the peaks of Mount Doom and build with intensity...",
        },
    },
    ["The Mire"] = {
        timer_minutes = 15,
        messages = {
            "The gurgling of the swamp can be heard around you...",
        },
    },
    ["Mithril Hall"] = {
        timer_minutes = 15,
        messages = {
            "Mithril Hall rumbles as a deep cry erupts from Garumn's Gorge...",
        },
    },
    ["Morgul Vale"] = {
        timer_minutes = 25,
        messages = {
            "A chorus of orcs begins to sing \"Where there's a whip, there's a way!\"",
        },
    },
    ["Moria"] = {
        timer_minutes = 15,
        messages = {
            "The silence is shattered as Moria's denizens awaken from slumber...",
        },
    },
    ["The Mountain of Lost Souls"] = {
        timer_minutes = 30,
        messages = {
            "Deep within the mountain, a tormented cry is heard as another soul is lost.",
        },
    },
    ["Mountains of Desolation"] = {
        messages = {
            "The wind around you howls the mournful tune of time past.",
        },
    },
    ["Nevermore"] = {
        timer_minutes = 40,
        messages = {
            "A flock of ravens circles ominously, their haunting caws broken by the whispering wind.",
        },
    },
    ["New Darkhaven"] = {
        timer_minutes = 15,
        silent = true,
        messages = {
            "Trumpets blare throughout Darkhaven, proclaiming a changing of the guard.",
        },
    },
    ["New Ofcol"] = {
        messages = {
            "Marshall Diana's footsteps can be heard patrolling the streets.",
        },
    },
    ["Northern Plains"] = {
        timer_minutes = 16,
        messages = {
            "Waves of wind wash through the tall grass like an ocean.",
        },
    },
    ["Northern Trade Route"] = {
        timer_minutes = 17,
        messages = {
            "The wind picks up along the lonely road, blowing debris and dust into the surrounding wilderness.",
        },
    },
    ["Ocean Keep"] = {
        timer_minutes = 20,
        messages = {
            "A ship's bell clangs in the distance.",
        },
    },
    ["Ockwater Fens"] = {
        timer_minutes = 75,
        messages = {
            "Time erodes the earth slightly further.",
        },
    },
    ["Octopus Garden"] = {
        timer_minutes = 15,
        messages = {
            "Clouds of silt erupt about you as yet another storm churns the waters about...",
        },
    },
    ["Ofcol"] = {
        messages = {
            "The hallowed echoes of magicks lost echo somewhere in the darkness.",
        },
    },
    ["Old Marsh"] = {
        messages = {
            "Shadowed figures rise from their watery graves...",
        },
    },
    ["Old Thalos"] = {
        messages = {
            "You hear some squeaking sounds...",
        },
    },
    ["Olympus"] = {
        timer_minutes = 15,
        messages = {
            "Thunder echoes from the skies as the Gods continue to battle against this existence...",
        },
    },
    ["Otherland"] = {
        timer_minutes = 25,
        messages = {
            "The temperature plummets as a storm moves in...",
        },
    },
    ["Pixie Forest"] = {
        timer_minutes = 6.5,
        messages = {
            "A pixie pops into view then flutters away, giggling...",
        },
    },
    ["Raven Tor"] = {
        messages = {
            "You feel a chill in your bones as time passes...",
        },
    },
    ["Realm of Worship"] = {
        messages = {
            "A quiet murmur trails through the cavern ...",
        },
    },
    ["Redferne's Residence"] = {
        timer_minutes = 16,
        messages = {
            "As if expecting Redferne, everything returns to the way it was before he left.",
        },
    },
    ["Revelation City"] = {
        timer_minutes = 15,
        messages = {
            "All grows silent as another falls from grace...",
        },
    },
    ["Salburg"] = {
        timer_minutes = 25,
        messages = {
            "A foul wind blows through the city, bringing with it despair and regret.",
        },
    },
    ["Scourge of Time"] = {
        timer_minutes = 7,
        messages = {
            "Dark sands twist and swirl like a gypsy dancer through hellfire...",
        },
    },
    ["Sea of Sorrows"] = {
        messages = {
            "Whispers of loves and battles lost can be heard over the ocean breezes...",
        },
    },
    ["Sentinel"] = {
        timer_minutes = 15,
        messages = {
            "The cry of a Skulk can be heard in the distance...",
        },
    },
    ["Seth's Fortress"] = {
        timer_minutes = 60,
        messages = {
            "The air around you heats and shimmers, as if consumed by flame ...",
        },
    },
    ["Sewer"] = {
        messages = {
            "The sound of rushing water can be heard echoing through the wasteland.",
        },
    },
    ["Shadow Grove"] = {
        messages = {
            "A blanket of fog crawls out of the forest...",
        },
    },
    ["Shadowport"] = {
        timer_minutes = 15,
        messages = {
            "A wave of cold passes through you, inspiring dread despair...",
        },
    },
    ["Shai'Ghool"] = {
        timer_minutes = 11,
        messages = {
            "A hiss of corrosion seeps from the darkness...",
        },
    },
    ["Shattered Refuge"] = {
        timer_minutes = 10,
        messages = {
            "The earth rumbles with the after-affects of another experiment gone awry...",
        },
    },
    ["The Shire"] = {
        timer_minutes = 14,
        messages = {
            "The streets bustle with the sounds of tiny feet on the move.",
        },
    },
    ["The Slime Pit"] = {
        timer_minutes = 45,
        messages = {
            "Sloshing, bubbling noises emerge from deep within the earth.",
        },
    },
    ["Southern Mountain Range"] = {
        timer_minutes = 15,
        messages = {
            "The rocks, hills and mountains continue to age with the world.",
        },
    },
    ["Temple of the Moon (Old)"] = {
        timer_minutes = 16,
        messages = {
            "A strange, serene feeling ripples through your body, putting you at ease.",
        },
    },
    ["Temple of the Moon"] = {
        timer_minutes = 20,
        messages = {
            "A soft harmony of adoration rings through the air...",
        },
    },
    ["Thalos"] = {
        timer_minutes = 16,
        messages = {
            "Swirls of dust dance as the wind howls through the empty streets...",
        },
    },
    ["The Curse of Prosperity"] = {
        timer_minutes = 22.5,
        messages = {
            "A moment of eerie silence overcomes the village.",
        },
    },
    ["Thul Ab'hara"] = {
        timer_minutes = 20,
        messages = {
            "A rhythmic chanting weaves its spell upon the desert wind...",
        },
    },
    ["Tower of Despair"] = {
        timer_minutes = 30,
        messages = {
            "Tortured screams echo throughout the tower, crying in supplication.",
        },
    },
    ["Tower of Enlightenment"] = {
        timer_minutes = 15,
        messages = {
            "Cries, screams, and laughter can be heard from the Tower's inhabitants...",
        },
    },
    ["Tower of Zenothir"] = {
        timer_minutes = 17,
        messages = {
            "Wails of distress can be heard off in the distance.",
        },
    },
    ["Town Hall"] = {
        messages = {
            "The sounds of angry peasants paying their damned taxes fills the Town Hall.",
        },
    },
    ["Town of Solace"] = {
        timer_minutes = 11,
        messages = {
            "The town crier's call rises above the din of the city.",
        },
    },
    ["Transylvania"] = {
        timer_minutes = 13,
        messages = {
            "An air of expectancy descends over the town, as the dead come home...",
        },
    },
    ["The Tree of Life"] = {
        timer_minutes = 15,
        messages = {
            "Branches rustle above as life continues ever onward...",
        },
    },
    ["Treetops and Canopy"] = {
        messages = {
            "The branches rustle as creatures move in search of food.",
        },
    },
    ["Tullfuhrzky Manor"] = {
        timer_minutes = 10,
        messages = {
            "A woman's nagging voice echoes from the manor house...",
        },
    },
    ["The Underworld"] = {
        timer_minutes = 45,
        messages = {
            "A sense of overwhelming malevolence seeps from the very heart of the underworld...",
        },
    },
    ["Unholy Grounds"] = {
        timer_minutes = 12,
        messages = {
            "The grief of mourners is audible throughout the burial ground...",
        },
    },
    ["Valley of Mysts"] = {
        timer_minutes = 10,
        messages = {
            "A lone wail wells up in the distance only to fade into the shadows.",
        },
    },
    ["Valley of the Elves"] = {
        timer_minutes = 18,
        messages = {
            "Elvish laughter drifts on the wind as you wander through the valley...",
        },
    },
    ["Village of Edo"] = {
        timer_minutes = 15,
        messages = {
            "A cloud passes by the sun as the rice fields are gently caressed by the wind.",
        },
    },
    ["The Von Deusen Mausoleum"] = {
        timer_minutes = 20,
        messages = {
            "The walls of the mausoleum drip with blood as the dead rise once more.",
        },
    },
    ["Warehouse"] = {
        timer_minutes = 6,
        messages = {
            "You hear a small child scream for his mommy.",
        },
    },
    ["Wastelands"] = {
        timer_minutes = 16,
        messages = {
            "A sudden burst of wind blows hollowly over the barren wastelands.",
        },
    },
    ["Wendle Mansion"] = {
        timer_minutes = 10,
        messages = {
            "The floorboards creak as the house begins to settle.",
        },
    },
    ["Western Trading Route"] = {
        timer_minutes = 37,
        messages = {
            "High above the open road, the shrill cry of a falcon can be heard.",
        },
    },
    ["Wild Tundra"] = {
        messages = {
            "The antarctic winds rise to a plaintive whine then die out...",
        },
    },
    ["World of Quests"] = {
        timer_minutes = 3,
        messages = {
            "You hear some squeaking sounds...",
        },
    },
    ["Wyvern's Tower"] = {
        timer_minutes = 15,
        messages = {
            "The caw of a flying beast echoes through the misty tower.",
        },
    },
    ["Ziggurat"] = {
        timer_minutes = 26,
        messages = {
            "A swift blow to end defiance, a thousand voices silenced in fire...",
        },
    },
    ["Shattered Temple of Naetrelle"] = {
        timer_minutes = 30,
        messages = {
            "The ancient temple shudders as the memories of a more innocent time fade into shadow.",
        },
    },
    ["Winterlight Island"] = {
        timer_minutes = 55,
        messages = {
            "A sharp, unnatural breeze chills you to the bone.",
        },
    },
    ["Corruption of Anciastra"] = {
        messages = {
            "Ancient and powerful magicks restore the energies throughout this land",
            "Ancient and powerful magicks restore the energies throughout this land.",
        },
    },
    ["Lamech's Abandoned Manor"] = {
        timer_minutes = 26,
        messages = {
            "Shadows twist and swirl as the undead rise to take ownership of the Manor.",
        },
    },
    ["The Mahn-Tor Catacombs"] = {
        timer_minutes = 15,
        messages = {
            "The ice seems to thicken on the catacomb walls as the chilled air swirls in a different direction.",
        },
    },
    ["The Southern Mountain Trade Route"] = {
        timer_minutes = 45,
        messages = {
            "Time moves ever onward, slowly shaping the mountainous landscape through erosion and deposition.",
        },
    },
    ["Dragontail Glen"] = {
        timer_minutes = 15,
        messages = {
            "The church bells sound in the distance and life in the Dragontail Glen continues.",
        },
    },
    ["Glimwinkle's Windmill"] = {
        timer_minutes = 27,
        messages = {
            "The incessant grinding sound of the windmill ceases for a moment, then clunks back into its regular rhythm.",
        },
    },
    ["The Barren Wastes"] = {
        timer_minutes = 24,
        messages = {
            "A slight breeze disrupts the still air of the stagnant landscape.",
        },
    },
    ["Fireball Island"] = {
        timer_minutes = 22,
        messages = {
            "The ground begins to shake violently as the volcano signals an imminent eruption.",
        },
    },
    ["Black Dagger Outlaws Hideout"] = {
        timer_minutes = 16,
        messages = {
            "Dice roll and liquor spills as the Black Dagger Outlaws plan their next heist.",
        },
    },
    ["Troll Den"] = {
        timer_minutes = 18,
        messages = {
            "A rather unpleasant smell wafts in from the north as the Trolls return to feed.",
        },
    },
    ["Blackraven Citadel"] = {
        silent = true,
        messages = {
            "Lightning crashes above Blackraven Citadel as all is reborn, and dragons cringe in fear...",
        },
    },
    ["Silvermoon Outpost"] = {
        timer_minutes = 28,
        messages = {
            "The bartender hums a tune, barely audible above the clank of ale mugs in the outpost.",
        },
    },
    ["From the Stars"] = {
        timer_minutes = 56,
        messages = {
            "Unrelenting winds sweep across the plains, while the secrets of the stars remain guarded.",
        },
    },
    ["Badlands"] = {
        messages = {
            "A bloodcurdling scream is heard in the distance, as another meets their fate...",
        },
    },
    ["Vast Horizons"] = {
        messages = {
            "The pace of thought quickens as the mind reaches forth...",
        },
    },
    ["Intrigues of the Miden'nir"] = {
        messages = {
            "Smoke continues to rise skyward from the smouldering forest.",
        },
    },
    ["Cold Comfort"] = {
        messages = {
            "A cracking, groaning noise can be heard as the ice shifts again.",
        },
    },
    ["The Domain of World Eater"] = {
        messages = {
            "Deep, booming laughter echoes through the halls of the citadel.",
        },
    },
    ["MacMillan Family Farm"] = {
        messages = {
            "A strong gust of wind is heard rattling through the orchards.",
        },
    },
    ["Southern Plains"] = {
        messages = {
            "The gentle breeze lightly teases the tops of nearby plants.",
        },
    },
}

rod.repop_areas_by_message = {}
for area_name, info in pairs(rod.repop_info) do
    for _, message in ipairs(info.messages) do
        local areas = rod.repop_areas_by_message[message] or {}
        table.insert(areas, area_name)
        rod.repop_areas_by_message[message] = areas
    end
end
